# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6e32f493e42a89474d693757fb16ffb23939caf0bedcad21f7fd14a6af777a48b506057b7e97b3306c06240b1b44df85830400740885a758471569f45da850d

test:
  secret_key_base: eba5eed55994d6c7f3985eef19fceb03ac415ed322b1938f1bc95d93e66bfeaba656e300a641ddd03d108da9e713d34e4da68464a9301e2ac30ceb36c7e79be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a6e32f493e42a89474d693757fb16ffb23939caf0bedcad21f7fd14a6af777a48b506057b7e97b3306c06240b1b44df85830400740885a758471569f45da850d

